### ISSUE TITLE
lipo reports x86_64 binary in libpng ARM build

### ISSUE THREAD

**Issue by nlandry** [gameplay3d/GamePlay-deps#10]
Doing lipo -info on the libpng archive (ARM version) shows armv7, v7s, 64, and x86_64.  The x86_64 bit is unexpected.  This started appearing once the neon files were included in the build (necessary for the lib to link).

Everything appears to work fine.  I think the only downside is a slightly bulkier lib.

**Comment by rgngl** [comment]
I will have a look at that in the evening when I get home.

**Comment by rgngl** [comment]
Forgot to look at that yesterday, but I don't think x86_64 binaries should be coming because of including the neon files.

Do you include the simulator build inside the same archive? If yes, simulator builds are 64-bits now if I'm not mistaken.
