### ISSUE TITLE
Project generation fails for VS 2015

### ISSUE THREAD

**Issue by louis-mclaughlin** [gameplay3d/GamePlay-deps#15]
`CMake Error at openal-1.16.0/CMakeLists.txt:439 (MESSAGE):
  No snprintf function found, please report!`

Project generates successfully when removing the snprintf detection. Also had to add the following for it to compile:

ADD_DEFINITIONS(-D_TIMESPEC_DEFINED)

**Comment by seanpaultaylor** [comment]
Can you submit the pull request for the changes you made. Then I will update the next branch to use VS 2015.

I got the same errors.  What did you change to remove the snprintf detection in openal ?

**Comment by louis-mclaughlin** [comment]
Yes, I'll have look at this at the weekend. Can't remember what I changed exactly, I think I had to remove some preprocessor definitions.

**Comment by seanpaultaylor** [comment]
I have now updated it to use VS 2015 in both master and next branch and updated the gameplay-deps.zip for all releases.
