### ISSUE TITLE
OpenAL include directory has wrong capitalisation.

### ISSUE THREAD

**Issue by JontomXire** [gameplay3d/GamePlay-deps#23]
The path of the OpenAL include files under the output directory external-deps/include is called "AL".
The include statement in GamePlay/gameplay/src/AudioController.h is for "Al/alc.h".

The capitalisation of the "l" differs.

I suspect that when I compiled GamePlay and all the samples that it was picking up a native include file rather than the one generated by GamePlay-deps.

It would be really nice if the integration between the two projects was better, e.g. by making Gameplay-deps a submodule of the GamePlay repo or something. I had to manually add a symlink and even then it appears that the compilation of GamePlay was picking up the wrong include file and possibly the wrong library file too.

**Comment by seanpaultaylor** [comment]
Seems like a quick fix issue in the GamePlay repo and not an issue in this repo.
Send a pull request to resolve.
