### ISSUE TITLE
GamePlay-deps cannot be built successfully for branch next-gen

### ISSUE THREAD

**Issue by openlabb** [gameplay3d/GamePlay-deps#25]
I built GamePlay-deps for MacOSX and failed (branch next-gen),here's the logs.Can anyone give some hints?

-- Directory: /Users/kklocal/Downloads/GamePlay-deps/out/external-deps/lib/macos/x86_64
-- Building with ZLIB
-- Building with BZip2
-- Building with PNG
-- Checking for module 'harfbuzz>=0.9.7'
--   No package 'harfbuzz' found
-- Creating directory /Users/kklocal/Downloads/GamePlay-deps/build/freetype-2.7.1/include/freetype/config
-- Creating file /Users/kklocal/Downloads/GamePlay-deps/build/freetype-2.7.1/include/freetype/config/ftconfig.h
-- Creating file /Users/kklocal/Downloads/GamePlay-deps/build/freetype-2.7.1/include/freetype/config/ftoption.h
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) (found version "1.0")
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) (found version "1.0")
-- Looking for ZLIB...
-- Checking for module 'zzip-zlib-config'
--   No package 'zzip-zlib-config' found
-- Found ZLIB: optimized;/usr/lib/libz.dylib;debug;/usr/lib/libz.dylib
-- Checking for module 'minizip'
--   No package 'minizip' found
-- Could NOT find rt (missing: RT_LIBRARY) 
INFO RT-extension not found. glTF import/export will be built without Open3DGC-compression.
-- Enabled formats: AMF 3DS AC ASE ASSBIN ASSXML B3D BVH COLLADA DXF CSM HMP IRRMESH IRR LWO LWS MD2 MD3 MD5 MDC MDL NFF NDO OFF OBJ OGRE OPENGEX PLY MS3D COB BLEND IFC XGL FBX Q3D Q3BSP RAW SIB SMD STL TERRAGEN 3D X X3D GLTF 3MF MMD
-- Disabled formats:
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/kklocal/Downloads/GamePlay-deps/build
[  0%] Linking CXX static library ../../../../out/external-deps/lib/macos/x86_64/libIrrXML.a
[  0%] Built target IrrXML
[  0%] Linking CXX static library ../../../out/external-deps/lib/macos/x86_64/libassimp.a
[ 55%] Built target assimp
[ 56%] Linking C static library ../../out/external-deps/lib/macos/x86_64/libfreetype.a
[ 68%] Built target freetype
[ 68%] Linking CXX static library ../../../../out/external-deps/lib/macos/x86_64/libjson.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../../../out/external-deps/lib/macos/x86_64/libjson.a(JSONAllocator.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../../../out/external-deps/lib/macos/x86_64/libjson.a(JSONDebug.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../../../out/external-deps/lib/macos/x86_64/libjson.a(JSONMemory.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../../../out/external-deps/lib/macos/x86_64/libjson.a(JSONNode_Mutex.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../../../out/external-deps/lib/macos/x86_64/libjson.a(JSONPreparse.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../../../out/external-deps/lib/macos/x86_64/libjson.a(JSONAllocator.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../../../out/external-deps/lib/macos/x86_64/libjson.a(JSONDebug.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../../../out/external-deps/lib/macos/x86_64/libjson.a(JSONMemory.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../../../out/external-deps/lib/macos/x86_64/libjson.a(JSONNode_Mutex.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../../../out/external-deps/lib/macos/x86_64/libjson.a(JSONPreparse.cpp.o) has no symbols
[ 72%] Built target json
[ 73%] Linking CXX static library ../../out/external-deps/lib/macos/x86_64/libtinyxml2.a
[ 73%] Built target tinyxml2
[ 74%] Linking C static library ../../../out/external-deps/lib/macos/x86_64/liblua.a
[ 83%] Built target lua
[ 84%] Linking C static library ../../out/external-deps/lib/macos/x86_64/libz.a
[ 88%] Built target zlib
[ 88%] Linking C static library ../../out/external-deps/lib/macos/x86_64/libpng.a
[ 92%] Built target png
[ 93%] Linking C static library ../../out/external-deps/lib/macos/x86_64/libogg.a
[ 93%] Built target ogg
[ 93%] Linking C static library ../../out/external-deps/lib/macos/x86_64/libvorbisenc.a
[ 93%] Built target vorbisenc
[ 93%] Linking C static library ../../out/external-deps/lib/macos/x86_64/libvorbisfile.a
[ 94%] Built target vorbisfile
[ 95%] Linking C static library ../../out/external-deps/lib/macos/x86_64/libvorbis.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../out/external-deps/lib/macos/x86_64/libvorbis.a(lookup.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../out/external-deps/lib/macos/x86_64/libvorbis.a(lookup.c.o) has no symbols
[100%] Built target vorbis
[100%] Generating libgameplay-deps.a
Using libtool : /usr/local/bin/libtool
Amalgamating target static libs /Users/kklocal/Downloads/GamePlay-deps/out/external-deps/lib/macos/x86_64
libtool: unrecognized option `-static'
libtool: Try `libtool --help' for more information.
[100%] Built target gameplay-deps

**Comment by seanpaultaylor** [comment]
Just tested on latest 10.13.x and all builds with latest code in nextgen.

**Comment by seanpaultaylor** [comment]
Make sure you have the latest xcode and xcode command line tools and you should be fine.
