### ISSUE TITLE
Lua lib no longer supports io.popen on Linux

### ISSUE THREAD

**Issue by louis-mclaughlin** [gameplay3d/GamePlay-deps#5]
I've got a gameplay game which uses some of lua's IO functions as part of a dev only tool-chain on Windows/Linux.

After upgrading the game to gameplay 3.0 + downloading the latest external-deps via install.sh, my lua tool-chain no longer works on Linux. Any script that I load that uses io.popen now fails to load because it's no longer supported:
```
loadScript -- Failed to load script: res/lua/tools.lua. [string "_toolsRoot = io.popen"pwd":read'*l'..."]:1: 'popen' not supported.
```

The readme in the lua-5.2.3/doc indicates that src/luaconf.h can be configured to enable io.popen on Linux by defining LUA_USE_LINUX. 

I tried to test and fix this myself by building gameplay-deps locally with this defined in CMakeLists.txt. Unfortunately, my game crashes when I use my locally built lib when trying to create an OpenAL device. I'd rather not try to fix this unrelated problem unless I have no alternative since I always intend to use the pre-built libs.

Was io.popen disabled on purpose? If not, can it be re-enabled for the sake backwards compatibility?

Thanks

**Comment by nlandry** [comment]
This was an oversight... Not done on purpose.  I'll have a patch in soon.

**Comment by nlandry** [comment]
Patch is in, I'll be updating the release in a bit.

**Comment by nlandry** [comment]
Okay, the gameplay-deps.zip has been updated.  Let me know how things go.

**Comment by louis-mclaughlin** [comment]
Yep that fixed it, much appreciated, thanks.
