### ISSUE TITLE
zlib declares Z_HAVE_UNISTD_H on Windows

### ISSUE THREAD

**Issue by rcmaniac25** [gameplay3d/GamePlay-deps#7]
zlib's zconf.h declares Z_HAVE_UNISTD_H which causes compile errors when used on Windows.

zlib is needed for https://github.com/gameplay3d/GamePlay/issues/1650

**Comment by nlandry** [comment]
Okay, I've patched the project and updated the release.  Should be okay now.  Let me know if anything else goes wrong.

**Comment by rcmaniac25** [comment]
I will take a look at it.

**Comment by rcmaniac25** [comment]
Sorry for the long delay, your update fixed the issue.
